Added extended entitlements
CESNET/perun-simplesamlphp-module pull request #138
Opened 2021-02-19 12:15 UTC by BaranekD

2021-02-22 12:42 UTC, vyskocilpavel requested changes

2021-02-22 12:42 UTC, vyskocilpavel commented on lib/EntitlementUtils.php
> +                'perun:PerunEntitlement: Object Perun User is not specified.' .
Should be ClassName:methodName

2021-02-22 12:42 UTC, vyskocilpavel commented on lib/EntitlementUtils.php
> +                'perun:PerunEntitlement: Exception ' . $exception->getMessage() .
Should be ClassName:methodName

2021-02-22 12:42 UTC, vyskocilpavel commented on lib/EntitlementUtils.php
> +                'perun:PerunEntitlement: Exception ' . $exception->getMessage() .
Should be ClassName:methodName

2021-02-22 12:42 UTC, vyskocilpavel commented on lib/EntitlementUtils.php
> +            throw new Exception('perun:PerunEntitlement: Cannot find entityID of remote SP. ' .
Should be ClassName:methodName

2021-02-22 12:42 UTC, vyskocilpavel commented on lib/Auth/Process/PerunEntitlementExtended.php
> +                'perun:PerunEntitlement: There are no user groups assign to facility.' .
Should be perun:PerunEntitlementExtended

2021-02-23 07:11 UTC, vyskocilpavel approved these changes

2021-02-23 09:42 UTC, dBucik requested changes

2021-02-23 09:42 UTC, dBucik commented on lib/Auth/Process/PerunEntitlementExtended.php
> +    private function groupNameWrapper($groupName)
I don't like the "groupName" wording there. Clearly, we are putting the UUID of the group as a parameter. As an external, I would probably get confused why this is happenning.

2021-02-23 09:42 UTC, dBucik commented on lib/Auth/Process/PerunEntitlementExtended.php
> +    private function groupEntitlementWrapper($groupName)
Same as above.

2021-02-23 09:42 UTC, dBucik commented on lib/Auth/Process/PerunEntitlementExtended.php
> +        return $this->entitlementPrefix . 'group:' . EntitlementUtils::encodeName($groupName) .
perhaps extracting the "group" as a constant would be a good idea.

2021-02-23 09:42 UTC, dBucik commented on lib/Auth/Process/PerunEntitlementExtended.php
> +        return $this->entitlementPrefix . 'group:' . $groupName . '#' . $this->entitlementAuthority;
Why isn't the groupName encoded? In the method above and below, we are encoding it, and here not.

2021-02-23 09:42 UTC, dBucik commented on lib/Auth/Process/PerunEntitlementExtended.php
> +    private function groupEntitlementWithAttributesWrapper($uuid, $groupName)
I think these wrapper methods should be extracted into the "utils" class as well as in the case of the capabilities wrapper.

2021-02-23 09:42 UTC, dBucik commented on lib/Auth/Process/PerunEntitlementExtended.php
> +            $groupName = preg_replace('/^(\w*)\:members$/', '$1', $groupName);
I would move these two lines either into the "wrapper" or closer to line 124 (as it uses it as a passed parameter).

2021-02-23 09:42 UTC, dBucik commented on lib/Auth/Process/PerunEntitlementExtended.php
> +    private function getEduPersonEntitlementExtended(&$request)
I see three output values for one group:
```
group:NAME
group:UUID
groupAttributes:UUID?...
```
Wasn't it agreed to leave out the NAME version?

2021-02-24 12:40 UTC, BaranekD commented
Requested changes done. I've also squashed commits into one.

2021-02-25 06:11 UTC, dBucik approved these changes

2021-03-02 10:27 UTC, merged