feat: Implemented EnsureVoMember filter
CESNET/perun-simplesamlphp-module pull request #166
Opened 2021-06-15 15:29 UTC by BaranekD

2021-06-18 06:58 UTC, vyskocilpavel commented
Waiting for the synchronization with the OIDC Implementation

2021-07-27 06:09 UTC, dBucik requested changes
Some small code improvements (in style, not in functionality), otherwise GTG by me.

2021-07-27 06:09 UTC, dBucik commented on lib/Auth/Process/EnsureVoMember.php
> +        $voShortName = $attrValues[$this->voDefsAttr];
to stay consistent with the code above, I would first do the assignment to the variable and then use it in the If statement :)

2021-07-27 06:09 UTC, dBucik commented on lib/Auth/Process/EnsureVoMember.php
> +    }
I don't like this construct. I would prefer if the parameters building would be the first block of code, like:
```
$params = [];
$params['StateId'] = $id;
$params['administrationContact'] = $request['SPMetadata']['administrationContact'];
$params['serviceName'] = $request['SPMetadata']['name']['en'];
if (isset($request['SPMetadata']['InformationURL']['en'])) {
    $params['informationURL'] = $request['SPMetadata']['InformationURL']['en'];
}
HTTP::redirectTrustedURL($url, $params);
```

It's a lot shorter :)

2021-07-27 06:09 UTC, dBucik commented on lib/Auth/Process/EnsureVoMember.php
> +    private function redirectDirectly($loginUrl, $voShortName)
Maybe rename the method to "redirectToRegistration" to better explaing what is the method doing.

2021-07-27 07:45 UTC, dBucik approved these changes

2021-07-27 08:57 UTC, vyskocilpavel requested changes
Missing example configuration

2021-07-28 10:29 UTC, vyskocilpavel approved these changes

2021-07-28 10:30 UTC, merged