feat: WAYF displays a name of the service
CESNET/perun-simplesamlphp-module pull request #168
Opened 2021-06-16 07:52 UTC by BaranekD

2021-06-18 06:55 UTC, vyskocilpavel commented on lib/Disco.php
> +            $this->spName = $translate->getPreferredTranslation($state[self::STATE_SP_METADATA][self::NAME]);
$state[self::STATE_SP_METADATA][self::NAME] can be null.

2021-11-01 12:16 UTC, dBucik requested changes

2021-11-01 12:16 UTC, dBucik commented on lib/Disco.php
> +        $translate = new Translate(Configuration::getInstance());
Please make use of the translation available in the template. Pass the template into the function and use it like `$t->t('{key}')`

2021-11-01 12:16 UTC, dBucik commented on lib/Disco.php
> +            $facility = $this->adapter->getFacilityByClientId($clientId);
Just to be sure, I would probably catch any exceptions thrown by the method. If we do not have the name, disco should work anyway.

2021-11-12 12:15 UTC, dBucik commented
@vyskocilpavel can you take a look and leave some feedback?

2021-11-24 09:01 UTC, merged